server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080


spring:
  profiles:
    active: dev

  mvc:
#    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiaocaizhengding.entity
  configuration:
    map-underscore-to-camel-case: true

# mapper
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

# pageHelper 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

debug: false

# 日志级别
logging:
  level:
    root: info
    com.sunforits.dao: debug
